[aws]
access_key_id = "YOUR_AWS_ACCESS_KEY_ID"
secret_access_key = "YOUR_AWS_SECRET_ACCESS_KEY"
session_token = "YOUR_AWS_SESSION_TOKEN"
bucket_name = "YOUR_S3_BUCKET_NAME"
region = "YOUR_AWS_REGION"
base_prefix = "YOUR_S3_BASE_PREFIX" 